### ISSUE TITLE
Donation key not supported for libraries

### ISSUE THREAD

**Issue by deathaxe** [jfcherng-sublime/ST-my-package-control#1]
Package Control doesn't support `donate` key for libraries.

PC4.0 will error out on it and ignore related libraries.

https://github.com/jfcherng-sublime/ST-my-package-control/blob/8db473d5dc3cd9abbc7e238e924e6f8f9f31654a/repository.json#L10

**Comment by jfcherng** [comment]
Thanks. Fixed.

**Comment by deathaxe** [comment]
Removing it from dependencies/libraries would have been enough.

It is supported by packages.

**Comment by jfcherng** [comment]
Lol. I am confused by the line you highlighted since it's a package but not a lib. But anyway, it's fine to remove them all.

**Comment by deathaxe** [comment]
Oups, sorry. It should have been

https://github.com/jfcherng-sublime/ST-my-package-control/blob/8db473d5dc3cd9abbc7e238e924e6f8f9f31654a/repository-released.json#L10
